### ISSUE TITLE
Use of tiago_description instead of tiago_dual_description

### ISSUE THREAD

**Issue by dnandha** [pal-robotics/tiago_dual_moveit_config#1]
https://github.com/pal-robotics/tiago_dual_moveit_config/blob/d70bc0b5617813a1e99daaea3afeb5b2d24480b0/launch/planning_context.launch#L18
Should be `tiago_dual_description` instead of `tiago_description`.

https://github.com/pal-robotics/tiago_dual_moveit_config/blob/d70bc0b5617813a1e99daaea3afeb5b2d24480b0/launch/planning_context.launch#L26
This line also have to be changed. For me `$(arg robot)` isn't set.

Otherwise this error is thrown:
`RLException: unused args [end_effector_right, end_effector_left, ft_sensor_left, ft_sensor_right] for include of [/opt/pal/ferrum/share/tiago_description/robots/upload.launch]
The traceback for the exception was written to the log file`

**Comment by v-lopez** [comment]
Thanks, looking into it.
